receivers:
  opencensus:

exporters:
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

service:
  pipelines:
    traces:
      receivers: [opencensus]
      exporters: [zipkin]