receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:55681"

exporters:
  opencensus:
    endpoint: "otel-collector:55678"
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [opencensus]